.gitignore
cabal.project
flake.lock
nix/materialized/aarch64-darwin/.plan.nix/plutus-certification.nix
nix/materialized/aarch64-darwin/default.nix
nix/materialized/x86_64-linux/.plan.nix/plutus-certification.nix
nix/materialized/x86_64-linux/default.nix
plutus-certification.cabal
src/Plutus/Certification/API.hs
src/Plutus/Certification/Cicero.hs
src/Plutus/Certification/Local.hs
src/Plutus/Certification/Server.hs

Adding support for aborting a Run

DAC-238: Abort a certification run

---

react-web/src/pages/certification/Certification.tsx
react-web/src/pages/certification/components/LogContainer.tsx
react-web/src/pages/certification/components/UnitTestFailureCard.tsx

https://input-output.atlassian.net/browse/DAC-254

[DAC-254] Display Unit Test failures in 'Finished' report in readable format

---

react-web/package-lock.json
react-web/package.json
react-web/src/components/TimelineItem/timeline.helper.tsx
react-web/src/compositions/Form/components/Input.tsx
react-web/src/hooks/useForm.ts
react-web/src/pages/certification/Certification.scss
react-web/src/pages/certification/Certification.tsx
react-web/src/pages/certification/certification.interface.ts
react-web/src/pages/certification/certification.schema.ts
react-web/src/pages/certification/components/LogContainer.tsx
react-web/yarn.lock

https://input-output.atlassian.net/browse/DAC-255
NB: Branch names are also acceptable

DAC-255 Add ability to accept commit hash

---

react-web/public/static/data/certifying.json
react-web/src/components/TimelineItem/TimelineItem.tsx
react-web/src/pages/certification/Certification.tsx

https://input-output.atlassian.net/browse/DAC-315

DAC-315 Fix for bug in Certifying progress timeline

---

react-web/src/components/charts/PieChart/PieChart.tsx
react-web/src/hooks/useLogs.ts
react-web/src/pages/certification/Certification.helper.tsx
react-web/src/pages/certification/Certification.scss
react-web/src/pages/certification/Certification.tsx
react-web/src/pages/certification/components/FailedStatus.tsx
react-web/src/pages/certification/components/ResultContainer.tsx
react-web/src/pages/certification/components/SuccessCard.tsx
react-web/src/utils/utils.ts

1. Change to fetch run-status in 5 seconds
2.  [DAC-349](https://input-output.atlassian.net/browse/DAC-349) show Unit test success cards in finished report
3. Fix for - 'View logs' should be always visible once logs are fetched
4. Updated colour palette in report Pie-chart slices to avoid bolder colours

[HOTFIX] Front-end fixes for demo

---

react-web/src/pages/certification/components/FileCoverageContainer.tsx

Changed current coverage-report label from coverage-file link to 'Coverage', for demo purposes

[For demo] Updated coverage-report label temporarily

---

dapps-certification-helpers/data/Certify.hs

As a short-term solution, it has been decided as the Backend should provide also the HTML file generated from the coverage report

feat: temporarly html report into certification result ( DAC-368 )

---

.gitignore
client/Main.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/API.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/Structure.hs
nix/materialized/aarch64-darwin/.plan.nix/plutus-certification.nix
nix/materialized/x86_64-darwin/.plan.nix/plutus-certification.nix
nix/materialized/x86_64-linux/.plan.nix/plutus-certification.nix
plutus-certification.cabal
src/Plutus/Certification/API/Routes.hs
src/Plutus/Certification/API/Swagger.hs
src/Plutus/Certification/Server.hs
src/Plutus/Certification/Web3StorageClient.hs

- API routes for creating the certification
- store certification info in DB
- store test runs into IPFS (through Web3 Storage gateway)

feat: start certification process and store report into ipfs (DAC-288)

---

client/Main.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/API.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/Structure.hs
server/Main.hs
src/Plutus/Certification/API/Routes.hs
src/Plutus/Certification/Server.hs

- authors , contacts and version for Profile
- commitHash for Run
- and prepare DApp entity for future changes

feat: data model changes ( DAC-397 )

---

react-web/package-lock.json
react-web/package.json
react-web/src/components/Modal/Modal.scss
react-web/src/components/Modal/Modal.tsx
react-web/src/pages/certification/Certification.tsx
react-web/src/pages/certification/components/FileCoverageContainer.tsx

**Imp: To be merged only after [DAC-317](https://github.com/input-output-hk/dapps-certification/pull/30)**
_See this link https://github.com/input-output-hk/dapps-certification/compare/DAC-317...DAC-387 for proper comparison of changes_

DAC-387 Coverage Report HTML

---

client/Main.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/API.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/Structure.hs
src/Plutus/Certification/API/Routes.hs
src/Plutus/Certification/API/Swagger.hs
src/Plutus/Certification/Server.hs

delete single test campaign DAC-361

feat: delete run (DAC-361)

---

client/Main.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/API.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/Structure.hs
src/Plutus/Certification/API/Routes.hs
src/Plutus/Certification/API/Swagger.hs
src/Plutus/Certification/Server.hs
src/Plutus/Certification/WalletClient.hs

BE has to provide through its API this wallet address is expecting payments

feat: wallet address route ( DAC-426 )

---

client/Main.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/API.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/Structure.hs
src/Plutus/Certification/API/Routes.hs
src/Plutus/Certification/API/Swagger.hs
src/Plutus/Certification/Server.hs
src/Plutus/Certification/WalletClient.hs

- the contacts and authors were left out from the current profile update (into db). this is the fix for it
also some non related fixes:
- descending order for runs history
- fixing API documentation missing fileds

fix: update authors and contacts into profile

---

src/Plutus/Certification/Server/Instance.hs

fixing the issue when for a private repo the creation of a test run tried to use the GitHub global access token instead of one saved into the profile

fix: not using the profile gh token for getting the commit-hash

---

nix/materialized/aarch64-darwin/.plan.nix/plutus-certification.nix
nix/materialized/x86_64-darwin/.plan.nix/plutus-certification.nix
nix/materialized/x86_64-linux/.plan.nix/plutus-certification.nix
plutus-certification.cabal
server/Main.hs
src/Plutus/Certification/Server/Instance.hs

add support for whitelisted addresses access only (this is an optional run mode of the service)

feat: addresses whitelist (DAC-485)

---

react-web/src/pages/subscription/Subscription.interface.ts
react-web/src/pages/subscription/SubscriptionContent.tsx
react-web/src/pages/subscription/components/PricingCard/PricingCard.tsx

this is a refactoring proposal based on some of the change requests in the targeted PR (#64)

Refactor: PLT-4562

---

Dockerfile.ws
client/Main.hs
dapps-certification-persistence/dapps-certification-persistence.cabal
dapps-certification-persistence/src/IOHK/Certification/Persistence.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/API.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/Structure.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/Structure/Profile.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/Structure/Subscription.hs
nix/materialized/aarch64-darwin/.plan.nix/dapps-certification-persistence.nix
nix/materialized/x86_64-darwin/.plan.nix/dapps-certification-persistence.nix
nix/materialized/x86_64-linux/.plan.nix/dapps-certification-persistence.nix
server/Main.hs
src/Plutus/Certification/API/Routes.hs
src/Plutus/Certification/API/Swagger.hs
src/Plutus/Certification/Cicero.hs
src/Plutus/Certification/Server/Instance.hs
src/Plutus/Certification/Server/Internal.hs
src/Plutus/Certification/Synchronizer.hs
src/Plutus/Certification/WalletClient.hs
src/Plutus/Certification/WalletClient/Transaction.hs

Entities relation
---------
```
+----------------+            +----------------------------------+                                
|      Tier      |            |            Subscription          |              +----------------+
------------------            |-----------------------------------              |   Profile      |
|                | 1        ∞ |                                  | ∞         1  |                |
| usdPrice       |<---------->|lovelacePrice                     |<-----------> |                |
| description    |            |startDate                         |              |                |
| expirationDays |            |status :: Active/Inactive/Pending |              |                |
| .......        |            |start/end :: Date                 | …
```

feat: add subscriptions support (PLT-4563)

---

nix/materialized/aarch64-darwin/.plan.nix/plutus-certification.nix
nix/materialized/x86_64-darwin/.plan.nix/plutus-certification.nix
nix/materialized/x86_64-linux/.plan.nix/plutus-certification.nix
plutus-certification.cabal
server/Main.hs
src/Plutus/Certification/CoinGeckoClient.hs
src/Plutus/Certification/Server/Instance.hs
src/Plutus/Certification/Synchronizer.hs

using CoinGecko API to establish the rate between ADA and USD

feat: external ada price (PLT-4295)

---

react-web/src/components/CreateCertificate/CreateCertificate.tsx

https://input-output.atlassian.net/browse/PLT-5543

PLT-5543 Show Amount to be paid with label change in Get Certificate btn

---

dapps-certification-persistence/src/IOHK/Certification/Persistence/API.hs

This PR is to fix the stuff I see should be changed when displayed on the FE. No algorithmic changes, just pure Text probably. This also means I haven't compiled it :sweat_smile:
Don't merge it yet, it's not done. I just messed up and sent it too early.

Fixing the stuff that the FE displays

---

dapps-certification-persistence/src/IOHK/Certification/Persistence/Pattern.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/Structure.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/Structure/Certification.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/Structure/Subscription.hs
server/Main.hs

Fixes [PLT-7678](https://input-output.atlassian.net/browse/PLT-7678)

chore: bypass server crash on sql data validation (PLT-7678)

---

dapps-certification-persistence/src/IOHK/Certification/Persistence.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/API.hs
nix/docker-files/docker.nix
server/Main.hs

Fixes [PLT-7673](https://input-output.atlassian.net/browse/PLT-7673)
Switch to using only one Sqlite Connection shared between all the jobs vs. the old approach with `withDb`

fix(sqlite): fixing the sqlite-lock (PLT-7673)

---

dapps-certification-persistence/src/IOHK/Certification/Persistence.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/API.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/Structure/Run.hs
nix/docker-files/docker.nix
server/Main.hs

Fixes [PLT-7670](https://input-output.atlassian.net/browse/PLT-7670)

fix(runs): abort all running tests after restart (PLT-7670)

---

dapps-certification-persistence/src/IOHK/Certification/Persistence/API.hs

I didn't compile it, I only changed the display text (I hope)

Small fixes in the text displayed when buying a subscription

---

dapps-certification-persistence/src/IOHK/Certification/Persistence.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/API.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/Structure.hs
nix/docker-files/docker.nix
src/Plutus/Certification/Synchronizer.hs
src/Plutus/Certification/WalletClient/Transaction.hs

fix(synchronizer): slow performance for synchronizing txs ( PLT-8268 )
Fixes: [PLT-8268](https://input-output.atlassian.net/browse/PLT-8268)

fix: slow transactions sync ( PLT-8268 )

---

client/Main.hs
dapps-certification-persistence/src/IOHK/Certification/Persistence/Structure.hs
src/Plutus/Certification/API/Routes.hs
src/Plutus/Certification/API/Swagger.hs
src/Plutus/Certification/Server/Instance.hs

-  allow profile elevated routes for current user 
- add `profileId` to ProfileDTO
Fixes [PLT-8553](https://input-output.atlassian.net/browse/PLT-8553)

feat: refine profile api ( PLT-8553 )

---

nix/docker-files/docker.nix
src/Plutus/Certification/Server/Instance.hs

TODO: before merging -> increase docker tag/version

fix(impersonation): role verification for run creation
